Public Class GameMapTiles
    Public Shared BLANK As String = "BLANK"
    Public Shared WALL As String = "WALL"
    Public Shared DESTROYABLE_WALL As String = "DESTRPYABLEWALL"
    Public Shared PLAYER_SPAWN As String = "PLAYERSPAWN"
    Public Shared BROWN_SPAWN As String = "BRWON_SPAWN"
    Public Shared GREY_SPAWN As String = "GREY_SPAWN"
    Public Shared TEAL_SPAWN As String = "TEAL_SPAWN"
    Public Shared YELLOW_SPAWN As String = "YELLOW_SPAWN"
    Public Shared RED_SPAWN As String = "RED_SPAWN"
    Public Shared GREEN_SPAWN As String = "GREEN_SPAWN"
    Public Shared PURPLE_SPAWN As String = "PRUPLE_SPAWN"
    Public Shared WHITE_SPAWN As String = "WHITE_SPAWN"
    Public Shared BLACK_SPAWN As String = "BLACK_SPAWN"
End Class